import numpy as np
import csv
import sys
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from feature_extraction import extract_dataset

def load_csv(path):
    with open(path, 'r') as f:
        reader = csv.reader(f)
        data = np.array([[float(v) for v in row] for row in reader])
    return data

def export_for_firmware(clf, output_path):
    """
    Export LDA coefficients as a C header file for Arduino firmware.
    LDA inference = argmax over classes of (coeff_vector · features)
    """
    coef      = clf.coef_
    intercept = clf.intercept_
    classes   = clf.classes_

    lines = []
    lines.append("// Auto-generated by train_classifier.py — do not edit manually")
    lines.append(f"#define NUM_GESTURES {len(classes)}")
    lines.append(f"#define NUM_FEATURES 4")
    lines.append("")
    lines.append("const float lda_coeff[NUM_GESTURES][NUM_FEATURES] = {")
    for i, row in enumerate(coef):
        formatted = ", ".join(f"{v:.6f}" for v in row)
        lines.append(f"    {{ {formatted} }},  // {['rest','open','close','pinch'][i]}")
    lines.append("};")
    lines.append("")
    lines.append("const float lda_intercept[NUM_GESTURES] = {")
    lines.append(f"    {', '.join(f'{v:.6f}' for v in intercept)}")
    lines.append("};")

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Firmware header exported to {output_path}")

def train(data_path, output_path):
    raw    = load_csv(data_path)
    X, y   = extract_dataset(raw)

    clf       = LinearDiscriminantAnalysis()
    cv_scores = cross_val_score(clf, X, y, cv=StratifiedKFold(n_splits=5), scoring='accuracy')
    print(f"5-fold CV accuracy: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

    clf.fit(X, y)
    print(classification_report(clf.predict(X), y,
          target_names=['rest','open','close','pinch']))
    export_for_firmware(clf, output_path)
    return clf

if __name__ == "__main__":
    data_path   = sys.argv[1] if len(sys.argv) > 1 else "data/emg_recordings.csv"
    output_path = sys.argv[2] if len(sys.argv) > 2 else "firmware/lda_model.h"
    train(data_path, output_path)
